Added extra request to registry/{package}/latest for .readmeText attribute
cpmteam/cpmteam.github.io pull request #3
Opened 2017-01-27 23:27 UTC by tsafin

We have discovered the harder way that /-/all request to registry does not return .readmeText attribute,
but particular request for /:packageName/:version does return all attributes, so invoking subrequest for this attribute.

2017-01-28 14:46 UTC, daimor requested changes

2017-01-28 14:46 UTC, daimor commented on src/services/dataSrvc.js
> +      getUrlData: function (url, cb) {
Should be changed to method getPackageData, which returns data by package name, and repository URL as a constant in this class.

2017-01-28 14:46 UTC, daimor commented on src/controllers/repoCtrl.js
> +    DataSrvc.getUrlData('https://cpmisc.smileupps.com/' + packageName + '/latest', function(data) {
conditional loading readmeText, if it was not loaded before.

2017-01-28 14:59 UTC, tsafin commented on src/services/dataSrvc.js
> +      getUrlData: function (url, cb) {
[Actually it is generic enough that's why I named it getUrlData.] 
In this case it's actually not a _constant_ but rather a function of the url used in the getData (we should name it getAllData). The hardcoded url is a bad hack to see it working. I'll update it to use not-constant value in the next step.

2017-01-28 14:59 UTC, tsafin commented on src/controllers/repoCtrl.js
> +    DataSrvc.getUrlData('https://cpmisc.smileupps.com/' + packageName + '/latest', function(data) {
Yeah, good point. Will change

2017-01-29 07:30 UTC, daimor approved these changes

2017-01-29 07:31 UTC, merged